// <auto-generated />
using CursosDeIdiomasWebAPI.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CursosDeIdiomasWebAPI.Migrations
{
    [DbContext(typeof(CursoDeIdiomasDbContext))]
    [Migration("20241020091426_VinculoTurmaAluno")]
    partial class VinculoTurmaAluno
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AlunoTurma", b =>
                {
                    b.Property<string>("listAlunosCPF")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("listTurmasCodigo")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("listAlunosCPF", "listTurmasCodigo");

                    b.HasIndex("listTurmasCodigo");

                    b.ToTable("AlunoTurma", (string)null);
                });

            modelBuilder.Entity("CursosDeIdiomasWebAPI.Models.Aluno", b =>
                {
                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("CodigoTurma")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("CPF");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("CursosDeIdiomasWebAPI.Models.Turma", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Codigo");

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("AlunoTurma", b =>
                {
                    b.HasOne("CursosDeIdiomasWebAPI.Models.Aluno", null)
                        .WithMany()
                        .HasForeignKey("listAlunosCPF")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CursosDeIdiomasWebAPI.Models.Turma", null)
                        .WithMany()
                        .HasForeignKey("listTurmasCodigo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
