// <auto-generated />
using CursosDeIdiomasWebAPI.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CursosDeIdiomasWebAPI.Migrations
{
    [DbContext(typeof(CursoDeIdiomasDbContext))]
    partial class CursoDeIdiomasDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CursosDeIdiomasWebAPI.Models.Aluno", b =>
                {
                    b.Property<string>("CPF")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.HasKey("CPF");

                    b.ToTable("Alunos");
                });

            modelBuilder.Entity("CursosDeIdiomasWebAPI.Models.Turma", b =>
                {
                    b.Property<string>("Codigo")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("AlunoCPF")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Codigo");

                    b.HasIndex("AlunoCPF");

                    b.ToTable("Turmas");
                });

            modelBuilder.Entity("CursosDeIdiomasWebAPI.Models.Turma", b =>
                {
                    b.HasOne("CursosDeIdiomasWebAPI.Models.Aluno", "Aluno")
                        .WithMany()
                        .HasForeignKey("AlunoCPF");

                    b.Navigation("Aluno");
                });
#pragma warning restore 612, 618
        }
    }
}
